name = "poha-worker"
main = "src/index.ts"
compatibility_date = "2025-04-01"
account_id = "b3cca244b478c41574e09cb0adef1a60"

[[kv_namespaces]]
binding = "ATTESTATIONS"
id = "108924792498428f8100a58f4a59e16d"
preview_id = "6dccdd9dc3984b8993dd1b630cb2230b"

[durable_objects]
bindings = [
  { name = "RATE_LIMITER", class_name = "RateLimiterDO" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RateLimiterDO"]

