import { describe, expect, test } from "bun:test";
import { renderVerifyPage, render404Page, renderLandingPage } from "../src/verify-page.js";
import type { StoredAttestation } from "../src/types.js";

describe("renderVerifyPage", () => {
  const stored: StoredAttestation = {
    attestation: {
      poha_version: "0.1",
      content_hash: "sha256:" + "a".repeat(64),
      effort_score: 0.82,
      effort_band: "high",
      composition_duration_ms: 45000,
      input_method: "web_keyboard",
      final_text_length: 312,
      timestamp_hour: "2026-04-01T14:00:00.000Z",
      signer_pubkey: "ed25519:abc123",
      signature: "ed25519:def456",
    },
    created_at: "2026-04-01T14:30:00.000Z",
    short_id: "Ab12x",
  };

  test("renders valid HTML", () => {
    const html = renderVerifyPage(stored);
    expect(html).toContain("<!DOCTYPE html>");
    expect(html).toContain("</html>");
  });

  test("includes badge ID", () => {
    const html = renderVerifyPage(stored);
    expect(html).toContain("Ab12x");
  });

  test("includes effort band label", () => {
    const html = renderVerifyPage(stored);
    expect(html).toContain("High effort");
  });

  test("includes 'Typed by hand' hero", () => {
    const html = renderVerifyPage(stored);
    expect(html).toContain("Typed by hand");
  });

  test("formats duration correctly", () => {
    const html = renderVerifyPage(stored);
    expect(html).toContain("45 sec");
  });

  test("uses green color for high effort", () => {
    const html = renderVerifyPage(stored);
    expect(html).toContain("#22c55e");
  });

  test("uses pen emoji as hero icon, not shield", () => {
    const html = renderVerifyPage(stored);
    expect(html).toContain("hero-emoji");
    expect(html).not.toContain("shield-icon");
  });

  test("explainer does not overclaim", () => {
    const html = renderVerifyPage(stored);
    expect(html).not.toContain("proves the message was composed by a human");
    expect(html).not.toContain("not generated by AI");
    expect(html).toContain("direct keyboard interaction");
    expect(html).toContain("never what was typed");
  });

  test("technical details collapsed in <details>", () => {
    const html = renderVerifyPage(stored);
    expect(html).toContain("<details>");
    expect(html).toContain("<summary>Technical details</summary>");
    expect(html).toContain("sha256:" + "a".repeat(64));
  });

  test("timestamp is hour-rounded, no minutes", () => {
    const html = renderVerifyPage(stored);
    // Should show hour only (e.g. "2 PM"), not "2:30 PM"
    expect(html).not.toContain("2:30");
  });

  test("input method is humanized", () => {
    const html = renderVerifyPage(stored);
    expect(html).toContain("Keyboard");
    expect(html).not.toContain("web_keyboard");
  });

  test("includes CTA to get badge", () => {
    const html = renderVerifyPage(stored);
    expect(html).toContain("Get your own badge");
    expect(html).toContain("poha.ink");
  });

  test("escapes HTML in user-controlled fields", () => {
    const xssStored: StoredAttestation = {
      ...stored,
      short_id: '<script>alert(1)</script>',
      attestation: {
        ...stored.attestation,
        signer_pubkey: 'ed25519:<img onerror=alert(1)>',
      },
    };
    const html = renderVerifyPage(xssStored);
    expect(html).not.toContain("<script>");
    expect(html).not.toContain("<img");
    expect(html).toContain("&lt;script&gt;");
  });

  test("includes CSP and security headers", () => {
    const html = renderVerifyPage(stored);
    expect(html).toContain("Content-Security-Policy");
    expect(html).toContain("X-Content-Type-Options");
    expect(html).toContain("X-Frame-Options");
  });

  test("says Proof of Human Attention", () => {
    const html = renderVerifyPage(stored);
    expect(html).toContain("Proof of Human Attention");
    expect(html).not.toContain("Proof of Human Authorship");
  });
});

describe("render404Page", () => {
  test("renders valid HTML", () => {
    const html = render404Page();
    expect(html).toContain("<!DOCTYPE html>");
    expect(html).toContain("Badge Not Found");
  });

  test("mentions expiration", () => {
    const html = render404Page();
    expect(html).toContain("expired");
  });

  test("includes security headers", () => {
    const html = render404Page();
    expect(html).toContain("Content-Security-Policy");
    expect(html).toContain("X-Content-Type-Options");
  });
});

describe("renderLandingPage", () => {
  test("renders valid HTML with branding", () => {
    const html = renderLandingPage();
    expect(html).toContain("<!DOCTYPE html>");
    expect(html).toContain("Proof of Human Attention");
    expect(html).toContain("Start typing");
  });

  test("links to web.poha.ink", () => {
    const html = renderLandingPage();
    expect(html).toContain("web.poha.ink");
  });

  test("includes CSP", () => {
    const html = renderLandingPage();
    expect(html).toContain("Content-Security-Policy");
  });
});
