name: Deploy Worker

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - 'packages/worker/**'
      - 'packages/sdk/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: oven-sh/setup-bun@v2

      - run: bun install

      - run: bun run --cwd packages/sdk build

      - uses: cloudflare/wrangler-action@v3.14.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: packages/worker
          wranglerVersion: "3.114.0"
